### ISSUE TITLE
Out of box installer does not work for MacOS

### ISSUE THREAD

**Issue by lsh** [ladybug-tools/ladybug-grasshopper#12]
Hello, today I installed ladybug-grasshopper with ladybug[+] on my Mac running Mojave. The process involved a little digging so I thought it might be helpful to list it here (or hopefully it may help in making a Mac installer at some point).

1. Download Honeybee[+] from [Food4Rhino](https://www.food4rhino.com/app/ladybug-tools) (it has Ladybug files too)
2. Install ghuser objects in user objects folder
3. In grasshopper run in a ghpython component

```python
import sys
print sys.path
```
The component will output a folder path which is where the python libs in Grasshopper are stored on Mac. In the output folder, drag the ladybug and honeybee folder from the Honeybee[+] download.
4. Download [ladybug-rhino from GitHub](https://github.com/ladybug-tools/ladybug-rhino)
5. Install the ladybug-rhino folder in the location from step 3

The install so far throws no errors from EPW files, however the ```LadybugPlus_EPWmap``` component throws the following error when toggled to true
```
close_fds is not supported on .NET platforms
```

**Comment by chriswmackey** [comment]
Thank you very much for testing and reporting this @lsh .  And thank you also for posting this issue in the correct repo (I know we have a lot now and I realize it probably took some time to find the right one).  This type of information is very helpful since neither @mostaphaRoudsari nor I have Macs but we know that Honeybee[+] should be fully supported on Rhino for Mac.

So we should be able to get the "out-of-the-box" installer to work on Mac for our next release of the [+] plugins but it would be really helpful if you could run a quick test for us to see if our assumptions are correct.  Specifically, could you follow steps 1-2 and then run the ["HoneybeePlus Installer" component](https://github.com/ladybug-tools/honeybee-grasshopper/blob/master/plugin/grasshopper/src/HoneybeePlus%20Installer.py) as the only component on the canvass. You will see that the code in that component is using `sys.path` and it should be able to take care of steps 3-5 for you automatically.  Please let us know otherwise.  If we get that to work, we should be able to put together an "out-of-the-box" installer that works on Mac.

As for the EPWmap component error, let's open another issue on this repo and see if we can get it fixed.

**Comment by chriswmackey** [comment]
FYI, here's the other issue where we will work to get the EPWmap component to work: https://github.com/ladybug-tools/ladybug-grasshopper/issues/13

**Comment by lsh** [comment]
Thank you for the quick response!

The installer threw a few errors as follows:
1. When run from the ```installer.gh``` file from honeybee-grasshopper.0.0.04 I get the error
```Runtime error (ValueErrorException): Cannot find scripts directory under Rhino Installation.```
2. When run using the linked installer component you referenced above and having _update as a the component input, I get the following error
```
Runtime error (IndexOutOfRangeException): index out of range: 0

Traceback:
  line 61, in updateHoneybee, "<string>"
  line 170, in script
```

**Comment by chriswmackey** [comment]
Hm. That is odd but we should still be able to get it to work.  What do you get when you `print sys.path` in your original script you posted here?  Is there no `scripts` folder within the folder that gets printed?  Also, for your original steps, do you just copy the ladybug tools libraries directly into the `sys.path` folder?

**Comment by lsh** [comment]
There is a Rhino scripts folder, but part of the install process for involved realizing that GHPython on Mac doesn't pull the lib from the scripts dir under Rhino. Instead, sys.path prints the following:
```/Applications/Rhinoceros.app/Contents/Frameworks/RhCore.framework/Versions/Current/Resources/ManagedPlugIns/RhinoDLR_Python.rhp/Lib```

**Comment by lsh** [comment]
I copied the the ladybug & honeybee python libs directly into the folder mentioned above. I copied the userobject components to the following folder:
```/Library/Application Support/McNeel/Rhinoceros/6.0/Plug-ins/Grasshopper (b45a29b1-4343-4035-989e-044e8580d9cf\)/UserObjects/```

**Comment by chriswmackey** [comment]
Thank you for all of the helpful information @lsh .  I believe that the fix I just pushed to the `Updater` component should allow you to install all of the libraries on Mac (taking care of steps 3-5):
https://github.com/ladybug-tools/honeybee-grasshopper/commit/3d7fe277c74673f385520674eda80d2cb172628d

Can you confirm whether this is the case when you get the chance?

**Comment by lsh** [comment]
I get a new error now:
```
Runtime Error (MissingMemberException): 'list' object has no attribute 'endswith'

Traceback:
  line 68, in join, "/Applications/Rhinoceros.app/Contents/Frameworks/RhCore.framework/Versions/Current/Resources/ManagedPlugins/RhinoDLR_Python.rhp/Lib/posixpath.py"
  line 71, in updateHoneybee, "<string>"
  line 167, in script
```

**Comment by chriswmackey** [comment]
Thanks for checking this so quickly @lsh and sorry that I made a blunder in my previous change.  I just pushed another, which should fix it:
https://github.com/ladybug-tools/honeybee-grasshopper/commit/18d5b32a8637e3e3e956aaf97cf7f8963ee5e0ca

Can you test it again now?

**Comment by lsh** [comment]
So all of the python libs installed just fine, but the user objects still threw an error. The last functional output is as follows:
```Copying ladybug[+] userobjects to /Users/lukas/Library/Application Support/McNeel/Rhinoceros/6.0/Plug-ins/Grasshopper (b45a29b1-4343-4035-989e-044e8580d9cf)/UserObjects/.```
and I did see a ladybug folder created in the UserObjects directory, but it was empty.

The error is as follows:
```
Runtime error (Win32Exception) : WindowsError

Traceback:
  line 159, in updateHoneybee, "<string>"
  line 172, in script
```

**Comment by chriswmackey** [comment]
Thanks again for testing this quickly @lsh . Unfortunately, that error message is not very helpful (there really should be a more descriptive message for a failure like this).

Can you paste the full output of Vviiiiizzzzz! so that I can see if anything else went wrong.  Also, can you confirm whether you were starting with an empty UserObjects folder before running the component or were there already folders with .ghuser files in there.

**Comment by chriswmackey** [comment]
Actually, could you try one more thing for me: Can you just insert the following line of code on line 158 of the component like so:
```
print userObjectsFolder
```
![image](https://user-images.githubusercontent.com/5567574/64718339-ff4c9200-d493-11e9-8a67-26e646c85319.png)

Then, let me know what it prints and whether there actually is a folder at that location.
I think, if I know that, I should be able to get it to work.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, based on the error up there the folder is probabaly `/Users/lukas/Library/Application Support/McNeel/Rhinoceros/6.0/Plug-ins/Grasshopper (b45a29b1-4343-4035-989e-044e8580d9cf)/UserObjects/`. Not sure if shutil is able to handle the white-spaces in the path. You most likely need to put the path in quotes.

**Comment by chriswmackey** [comment]
Could you elaborate on what you mean @mostaphaRoudsari ?  `shutil.copyfile` has been able to handle white spaces in other cases that I have tested.  And, judging from the line where the error is happening, I think the issue is with `os.listdir` and not `shutil`.  That's why I asked if @lsh can print the `useObjectsFolder` that is downloaded and not the `plus_uofolder`, which seems to be working fine.

Actually, now that I have looked closer at it, I am wondering if it's because we are using forward slashes instead of backwards slashes int he file path.  Let me put together another commit and, @lsh , if you could still let me know what you get when you print the userObjectFolder, that would be great.

**Comment by lsh** [comment]
Successful install!!!! :)

**Comment by chriswmackey** [comment]
Woohoo!  Thank you for your persistence @lsh !
