### ISSUE TITLE
Change hoys inputs to moys or datetime 

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-grasshopper#14]
This is a proposal for all the Ladybug Tools plugins but I think we should start with Ladybug. There are a number of components, I can remember sunpath for one, that take the hour of the year as an input which works fine for hourly workflow but is not the best option when it comes to sub-hourly set-up. We end up with strange float numbers that we have to translate back and forth to minutes or datetime.

My proposal is to use minute of the year or datetime instead. Minute of the year will be the most efficient and datetime will be the most readable option.

What are your thoughts on this @chriswmackey?

**Comment by chriswmackey** [comment]
Sorry for the late response here @mostaphaRoudsari . This one slipped through my radar. 

Personally, I find the use of hoys on the interface end quite ideal as long as people have the option to use decimal values for sub-hourly times (as they do now). 

Granted, within the core libraries, I agree that using moys for everything makes sense since it's there that we need to enforce things like using integers for moys (making it clear to API-users that we don't support accuracy to the level less than a minute).

But I don't think these same highly-technical needs exist on the Grasshopper interface end and I feel that we should let the interface be good at being interface. That is, tailoring interface inputs to be for the most common use cases rather than to the most technical or specific use cases. I think it's much more common that people want to align sun positions with hourly data and hourly indices rather than minute data and minute indices.  So I think it makes sense to use hoys in the interface and, if people need to align the positions with finer data, I don't think that multiplying the hoy by 60 (or whatever the timestep of their data is) is a big ask for these people.

**Comment by chriswmackey** [comment]
Now that we are at the release, I think this one is settles so I'm closing it out.
