### ISSUE TITLE
LB Unit Converter reporting incorrect data type for clo, not listing ClothingInsulation.

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/ladybug-grasshopper#206]
@chriswmackey 

@kelsworth found what looks like a bug in the LB Unit Converter component, and also possibly in the way the ladybug.datatypes.UNITS dictionary is being defined. 

As you can see in the image below, the all_u output doesn't list the ClothingInsulation data type at all, and the clo unit is listed as part of the units for RValue. And the LB PMV Comfort component fails to read clo values unless it is defined as a ClothingInsulation data type. 

![image](https://user-images.githubusercontent.com/1685956/110990239-0ed6c080-8341-11eb-95a4-374efbf0036a.png)

**Comment by chriswmackey** [comment]
@saeranv ,
This is intentional. The `ClothingInsulation` data type inherits from the `RValue` data type.

There are [a lot more sub-classed data types available if you check the ladybug.datatype.TYPES constant](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/datatype/__init__.py#L23) but, if I were to show all of the inheriting data types as an output of `all_u`, the result would be so dense that it wouldn't really be readable.

If it helps, I can relax the type-checking on the PMV method so that it will accept all `RValue` data types (including all children). I guess that would probably still catch a lot of cases where people accidentally connect the wrong data type to the input. Yet it wouldn't be as annoying here since you can use the RValue data type for your clothing data collection.

**Comment by chriswmackey** [comment]
I just relaxed the type-checking in ladybug-comfort:
https://github.com/ladybug-tools/ladybug-comfort/pull/271

Feel free to reopen the issue if you think this does not address the concern.

**Comment by saeranv** [comment]
Thanks @chriswmackey, I think relaxing the type-checking is a good fix. That way you avoid the situation where the all_u output indicates you can use RValue to define clo, but then PMV throws an error as soon as you try it.
