### ISSUE TITLE
LB+ Versioner python path and HB libraries issues

### ISSUE THREAD

**Issue by BingWangUS** [ladybug-tools/ladybug-grasshopper#64]
Hi, I did a quick search in the forum but did not find anyone reporting this after the recent release so putting here as I think this may be a small coding issue.

1. 
The LB versioner component is giving me a error on python path. As I don't think the latest release (0.0.6 installer.gh) is installing python into this location, this could be solved by giving a user input for python path. 

![image](https://user-images.githubusercontent.com/10835375/87880336-fb947080-c9be-11ea-88fe-7e5bf378ba65.png)

2.
I noticed the versioner will install HB, HB-Radiance, HB-Radiance, but the necessary libraries (scripts\honeybee, honeybee_energy, honerbee_radaince, honerbee_standard) are not installed at the same time. The Legacy updaters, HB+ installer are not installing those libraries either.

**Comment by mostaphaRoudsari** [comment]
Hi @chriswmackey, what are your thoughts on this one. I believe someone else had a similar issue.

**Comment by chriswmackey** [comment]
@BingWangUS ,

This is not a bug. It's just that this component is not for the version of Honeybee[+] you are using but rather for the newer plugin that is in beta (for better or for worse, the same ladybug-grasshopper package is used for both of these while we're in the midst of this transition). Use the HoneybeePlus Installer component instead of this one to sync your plugin with the github:
![image](https://user-images.githubusercontent.com/5567574/88959299-c534dc00-d26f-11ea-9efe-23f20850e923.png)

**Comment by BingWangUS** [comment]
@chriswmackey thanks Chris for looking into it. Understood, and looking forward to the new tools. For your reference, I'm also experiencing some HBPlus installer issue, raised here (https://github.com/ladybug-tools/honeybee-grasshopper/issues/44).
